version: '3.3'


volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    container_name: recipes_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
