version: '3.8'

services:
  web:
    container_name: recipes-fastapi
    build: .
    command: uvicorn recipes.app:app --reload --host 0.0.0.0 --port 8001
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - pg_db

  pg_db:
    image: postgres
    container_name: recipes_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  pg_project:
